spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daon_schema
    username: daonuser
    password: daon1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false