spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daon_schema
    username: daonuser
    password: daon1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 415045963497-6a4h12l94ovshlq70jmfjlh3susd8g91.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
jwt:
  secretKey: daonsecretdaonsecretdaonsecretdaonsecretdaonsecretdaonsecretdaonsecretdaonsecret